export * from './popUp/PopUp'
export * from './goalsList/SingleGoal'
export * from './shared/NavbarMenu'
export * from './shared/NavPage'
export * from './shared/Footer'
export * from './shared/Header'
export * from './homePage/MainHome'